[package]
name = "job_system"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
